### ISSUE TITLE
Escape the edit prompt by clicking outside

### ISSUE THREAD

**Issue by hugmatj** [Rubanthilak/kanban-board#4]
Heyo - keep your head up -

You made a thing that simply, flipping , works. 

I haven't looked @ your code yet but closing the edit prompt without hitting the X button would be a good quality of life change.

**Comment by rubanthilak** [comment]
Please don't look at the code. it's terrible. I created this repo when I started learning VueJS.
And Thanks for your suggestion. I will find sometime to fix it.
